# Generated by Django 3.2.6 on 2021-08-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estilo', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('pais_ingles', models.CharField(max_length=255)),
                ('alcohol', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('amargor', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=1024, null=True)),
                ('descripcion_ingles', models.CharField(blank=True, max_length=1024, null=True)),
                ('disponible', models.BooleanField(max_length=255)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('artesanal', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('recomendada', models.BooleanField()),
                ('formato', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('formato_2', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('formato_3', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sin_gluten', models.BooleanField(max_length=255)),
                ('aparece', models.BooleanField()),
                ('barril', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_ingles', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=1024, null=True)),
                ('descripcion_ingles', models.CharField(blank=True, max_length=1024, null=True)),
                ('tipo', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('altramuces', models.BooleanField()),
                ('apio', models.BooleanField()),
                ('cacahuete', models.BooleanField()),
                ('crustaceo', models.BooleanField()),
                ('gluten', models.BooleanField()),
                ('huevo', models.BooleanField()),
                ('lacteos', models.BooleanField()),
                ('moluscos', models.BooleanField()),
                ('mostaza', models.BooleanField()),
                ('nueces', models.BooleanField()),
                ('pescado', models.BooleanField()),
                ('sesamo', models.BooleanField()),
                ('soja', models.BooleanField()),
                ('sulfitos', models.BooleanField()),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_1', models.CharField(blank=True, max_length=1024, null=True)),
                ('titulo_1_ingles', models.CharField(blank=True, max_length=1024, null=True)),
                ('titulo_2', models.CharField(blank=True, max_length=1024, null=True)),
                ('titulo_2_ingles', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
