# Generated by Django 3.2.6 on 2021-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveza',
            name='sin_gluten',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio_2',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
