# Generated by Django 3.2.6 on 2021-09-05 17:46

from django.db import migrations, models
import django.db.models.deletion

def create_family(apps, schema_editor):
    Comida = apps.get_model('api', 'Comida')
    TipoComida = apps.get_model('api', 'TipoComida')
    for comida in Comida.objects.all():
        if comida.tipo:
            nombre, nombre_ingles = comida.tipo.split('-')
            tipo, _ = TipoComida.objects.get_or_create(nombre=nombre, nombre_ingles=nombre_ingles)
            comida.tipo = tipo.id
            comida.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cerveza_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_ingles', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Familia de comidas',
                'verbose_name_plural': 'Comidas',
            },
        ),
        migrations.RunPython(create_family),

        migrations.AlterField(
            model_name='comida',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocomida', null=True),
        ),
    ]
