# Generated by Django 3.2.6 on 2021-09-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210905_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocomida',
            options={'verbose_name': 'Familia de comida', 'verbose_name_plural': 'Familias de Comida'},
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='aparece',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='tipo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipocomida'),
            preserve_default=False,
        ),
    ]
