# Generated by Django 3.2.6 on 2021-09-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210908_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
